name: Run e2e-tests every 2 hours

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2h

jobs:
  # Run e2e tests on self-hosted runner
  integration-cron:
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -u golang.org/x/lint/golint
          go get -u golang.org/x/tools/cmd/goimports

      - name: Run e2e tests
        env:
          DISABLE_PROMPT: "true"
          RUN_CONFORMANCE: "true"
          TESTER_DIR: "."
          AWS_DEFAULT_REGION: "us-west-2"

        run: |
          ./scripts/run-integration-tests.sh

